name: release

on:
  push:
    branches:
      - release
  schedule:
    - cron: '45 5 * * *'

jobs:
  build:
    env:
     - DOCKER_ORG: miltonngan
     - DOCKER_REPO: docker-dummy
    strategy:
      matrix:
        build_cmd:
        - ./build-latest.sh
        - PRERELEASE=true ./build-latest.sh
        - ./build-next.sh
        - ./build.sh develop
      fail-fast: false
    runs-on: ubuntu-latest
    name: Builds new Netbox Docker Images
    steps:
    - id: git-checkout
      name: Checkout
      uses: actions/checkout@v2
    - id: docker-build
      name: Build the image with '${{ matrix.build_cmd }}'
      run: ${{ matrix.build_cmd }}
      env:
        GH_ACTION: enable
